export const demoProjects = [
  {
    name: "SmartTaskPro",
    repo: "demo/smarttaskpro",
    branch: "main",
    deployType: "cPanel",
    domain: "smarttaskpro-demo.com",
    server: "ftp.demo-server.com",
    deployPath: "/public_html",
    lastDeploy: "3 min ago",
    status: "success" as const,
    commits: 245,
  },
  {
    name: "EcommerceAPI",
    repo: "demo/ecommerce-api",
    branch: "staging",
    deployType: "Docker",
    domain: "api.ecommerce-demo.com",
    server: "docker.demo-server.com",
    deployPath: "/app",
    lastDeploy: "8 min ago",
    status: "running" as const,
    commits: 512,
  },
  {
    name: "PortfolioSite",
    repo: "demo/portfolio-site",
    branch: "main",
    deployType: "FTP",
    domain: "portfolio-demo.com",
    server: "ftp.demo-server.com",
    deployPath: "/public_html",
    lastDeploy: "25 min ago",
    status: "failed" as const,
    commits: 89,
  },
  {
    name: "ChatApp",
    repo: "demo/chat-app",
    branch: "develop",
    deployType: "VPS",
    domain: "chat-demo.com",
    server: "vps.demo-server.com",
    deployPath: "/var/www/chat",
    lastDeploy: "1 hour ago",
    status: "success" as const,
    commits: 178,
  },
  {
    name: "AnalyticsDash",
    repo: "demo/analytics-dash",
    branch: "main",
    deployType: "SFTP",
    domain: "analytics-demo.com",
    server: "sftp.demo-server.com",
    deployPath: "/var/www/analytics",
    lastDeploy: "2 hours ago",
    status: "success" as const,
    commits: 334,
  },
  {
    name: "BlogPlatform",
    repo: "demo/blog-platform",
    branch: "main",
    deployType: "Docker",
    domain: "blog-demo.com",
    server: "docker.demo-server.com",
    deployPath: "/app",
    lastDeploy: "5 hours ago",
    status: "pending" as const,
    commits: 67,
  },
];

export const demoPipelineSteps = [
  { id: "1", name: "Checkout Repository", command: "actions/checkout@v3", type: "checkout" as const },
  { id: "2", name: "Install Dependencies", command: "npm install", type: "install" as const },
  { id: "3", name: "Run Build", command: "npm run build", type: "build" as const },
  { id: "4", name: "Run Tests", command: "npm test", type: "test" as const },
  { id: "5", name: "Deploy", command: "lftp deploy", type: "deploy" as const },
];

export const demoDeploymentSteps = [
  { label: "Cloning repository", duration: 800 },
  { label: "Installing dependencies", duration: 1500 },
  { label: "Running build", duration: 2000 },
  { label: "Running tests", duration: 1200 },
  { label: "Deploying files to server", duration: 1800 },
  { label: "Deployment successful", duration: 500 },
];

export const demoStats = [
  { label: "Total Projects", value: "6", change: "+1 this week" },
  { label: "Deployments", value: "148", change: "+23 this week" },
  { label: "Success Rate", value: "94.6%", change: "+1.2%" },
  { label: "Avg Deploy Time", value: "2m 14s", change: "-12s" },
];

export const demoDeploymentHistory = [
  {
    id: "23",
    project: "SmartTaskPro",
    branch: "main",
    commit: "a83f9c2",
    status: "success" as const,
    time: "3 min ago",
    duration: "2m 14s",
    steps: [
      { name: "Checkout Repo", status: "success" as const, duration: "2s", log: "Cloning repository...\nChecked out branch 'main' at a83f9c2" },
      { name: "Install Dependencies", status: "success" as const, duration: "34s", log: "npm install\nadded 1423 packages in 34s" },
      { name: "Build", status: "success" as const, duration: "48s", log: "npm run build\n✓ 142 modules transformed\n✓ built in 48s" },
      { name: "Run Tests", status: "success" as const, duration: "22s", log: "npm test\n✓ 47 tests passed\n0 failures" },
      { name: "Deploy to FTP", status: "success" as const, duration: "18s", log: "Uploading to ftp.demo-server.com\n142 files uploaded\nDeploy complete!" },
    ],
  },
  {
    id: "22",
    project: "EcommerceAPI",
    branch: "staging",
    commit: "b73d9e1",
    status: "failed" as const,
    time: "15 min ago",
    duration: "1m 48s",
    steps: [
      { name: "Checkout Repo", status: "success" as const, duration: "2s", log: "Cloning repository...\nChecked out branch 'staging' at b73d9e1" },
      { name: "Install Dependencies", status: "success" as const, duration: "28s", log: "npm install\nadded 1891 packages in 28s" },
      { name: "Build", status: "failed" as const, duration: "38s", log: "npm run build\nERROR: Module not found: ./services/PaymentGateway\nBuild failed with 1 error" },
      { name: "Deploy", status: "failed" as const, duration: "-", log: "Skipped due to build failure" },
    ],
  },
  {
    id: "21",
    project: "PortfolioSite",
    branch: "main",
    commit: "c4e2a7f",
    status: "success" as const,
    time: "1 hour ago",
    duration: "1m 32s",
    steps: [
      { name: "Checkout Repo", status: "success" as const, duration: "2s" },
      { name: "Install Dependencies", status: "success" as const, duration: "22s" },
      { name: "Build", status: "success" as const, duration: "42s" },
      { name: "Deploy", status: "success" as const, duration: "26s" },
    ],
  },
  {
    id: "20",
    project: "ChatApp",
    branch: "develop",
    commit: "d9f1b3c",
    status: "success" as const,
    time: "3 hours ago",
    duration: "2m 05s",
    steps: [
      { name: "Checkout Repo", status: "success" as const, duration: "2s" },
      { name: "Install Dependencies", status: "success" as const, duration: "31s" },
      { name: "Build", status: "success" as const, duration: "55s" },
      { name: "Run Tests", status: "success" as const, duration: "19s" },
      { name: "Deploy to VPS", status: "success" as const, duration: "18s" },
    ],
  },
];

export const demoRecentActivity = [
  { action: "Deployed", project: "SmartTaskPro", detail: "to production via cPanel", time: "3 min ago" },
  { action: "Build failed", project: "EcommerceAPI", detail: "module not found error", time: "15 min ago" },
  { action: "Pipeline updated", project: "PortfolioSite", detail: "added test step", time: "30 min ago" },
  { action: "PR merged", project: "ChatApp", detail: "#38 add websocket support", time: "1 hour ago" },
  { action: "Project created", project: "BlogPlatform", detail: "new Docker deployment", time: "5 hours ago" },
];

export const demoPullRequests = [
  {
    id: 42,
    title: "Fix header responsive layout",
    project: "PortfolioSite",
    author: "admin",
    branch: "fix/header-layout",
    target: "main",
    status: "success" as const,
    comments: 3,
    time: "2 hours ago",
    additions: 45,
    deletions: 12,
  },
  {
    id: 38,
    title: "Add Docker deployment support",
    project: "EcommerceAPI",
    author: "admin",
    branch: "feature/docker",
    target: "staging",
    status: "running" as const,
    comments: 7,
    time: "5 hours ago",
    additions: 234,
    deletions: 56,
  },
  {
    id: 35,
    title: "Update CI pipeline configuration",
    project: "SmartTaskPro",
    author: "admin",
    branch: "ci/update-pipeline",
    target: "main",
    status: "success" as const,
    comments: 1,
    time: "1 day ago",
    additions: 18,
    deletions: 8,
  },
  {
    id: 31,
    title: "Refactor authentication module",
    project: "ChatApp",
    author: "admin",
    branch: "refactor/auth",
    target: "develop",
    status: "failed" as const,
    comments: 5,
    time: "2 days ago",
    additions: 189,
    deletions: 134,
  },
];
